### ISSUE TITLE
bower repository not found error

### ISSUE THREAD

**Issue by muratcorlu** [logicbomb/lvlDragDrop#24]
When I try to install lvlDragDrop via bower, I get an error that says repository not found. Did you changed your repository name or account?

```
> bower info lvlDragDrop
bower not-cached    git://github.com/reykjavik-university/lvlDragDrop.git#*
bower resolve       git://github.com/reykjavik-university/lvlDragDrop.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/reykjavik-university/lvlDragDrop.git", exit code of #128 fatal: remote error:    Repository not found.
```

**Comment by logicbomb** [comment]
That's not my repo, use this one - git@github.com:logicbomb/lvlDragDrop.git

**Comment by muratcorlu** [comment]
OK, I see. I think someone else has been registered a package named as lvlDragDrop to bower(maybe a fork of your project) but now it's unreachable. So, if someone wants to install your package via bower, he must install by your github repository url instead of `lvlDragDrop`

    bower install git://github.com/logicbomb/lvlDragDrop.git

**Comment by logicbomb** [comment]
I opened an issue with the Bower registry project: https://github.com/bower/registry/issues/132
